openapi: 3.0.1
info:
  version: '1.0'
  title: Product API
  description: 'Creating products.'
  contact:
    email: lvjian700@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT